<?php

return [
    'cumulated_alt' => 'Closed cases + interrupted cases + client client unreachable cases',

    'health_map' => 'Health Map',
    'law' => 'legal',
    'under_19' => 'under 19',
    'from_20_to_29' => 'age 20-29',
    'from_30_to_39' => 'age 30-39',
    'from_40_to_49' => 'age 40-49',
    'from_50_to_59' => 'age 50-59',
    'above_60' => 'above 60',
    'health_map_desc' => 'With the help of our new Mental Hygiene Health Map you could easily review and analyse the most used EAP areas, generated by your employees. Information is being displayed by age and gender ranges for the most popular areas. Data will be cumulated month by month so that in long run, more precise results will be shown on this Mental Hygiene Health Map. This map could be an ideal support for the HR team to better plan and form EAP internal communications as well as decide on possible topics for future workshops. Type of EAP counselling will be displayed on the map as well as categories for age. Results will be shown in this grid in smaller or larger circles by age ranges where larger circle will represent higher, smaller will represent lower utilisations.',
    'prize_game_desc' => 'You can see the number of participants of the prize game by scrolling down. The data is constantly updated according to the number of people participating in the game. After the prize game has ended, the drawing can be started with the ’Start draw’ button and stopped with the ’Stop draw’ button. Where the numbers stops, the participant associated with the displayed number wins, and their details appear below the number. The drawing can continue by pressing the ‘Start draw’ button and then pressing the ’Stop draw’ button until the desired number of winners is reached.',

    'live' => 'LIVE',

    'news' => 'New! Digital balance workshop',
    'number_of_calls' => 'Number of cases',
    'in_progress_cases' => 'Current, ongoing consultations',
    'in_progress_cases_short' => 'Active Cases by End of Report Period',
    'closed_cases' => 'Closed Cases',
    'cumulate' => 'CUMULATE',
    'cumulated_numbers' => 'All cumulated EAP interactions and utilizations',
    'interrupted_cases' => 'Interrupted Cases',
    'client_unreachable_cases' => 'CLIENT UNAVAILABLE CASES',
    'workshop_participants' => 'Workshop Participants',
    'orientation_participants' => 'Orientation Participants',
    'health_day_participants' => 'Health Day Participants',
    'expert_outplacement_participants' => 'Expert Outplacement Participants',
    'prizegame_participants' => 'Prizegame Participants',
    'valeo_workplace_1' => 'EAP use per site',
    'valeo_workplace_2' => 'EAP use per site',
    'hydro_workplace' => 'EAP use per site',
    'pse_workplace' => 'EAP use per site',
    'michelin_workplace' => 'EAP use per site',
    'sk_battery_workplace' => 'EAP use per site',
    'grupa_workplace' => 'EAP use per site',
    'robert_bosch_workplace' => 'EAP use per site',
    'gsk_workplace' => 'EAP use per site',
    'johnson_and_johnson_workplace' => 'EAP use per site',
    'syngenta_workplace' => 'EAP use per site',
    'nestle_workplace' => 'EAP use per site',
    'mahle_pl_workplace' => 'EAP use per site',
    'lpp_workplace' => 'EAP use per site',
    'amrest_workplace' => 'EAP usage per company group',
    'kuka_workplace' => 'KUKA sites',
    'crisis_participants' => 'Crisis Intervention Participants',
    'eap_logins' => 'EAP Online logins',
    'record' => 'the most commonly used counseling, based on gender and age',
    'record_problem_type' => 'Problem type',
    'record_gender' => 'Gender',
    'record_age' => 'Age',
    'gender_x_problem_type' => 'distribution of women and men by problem type',
    'age_x_problem_type' => 'AGE Distribution by Problem Type',
    'download' => 'DOWNLOAD EAP REPORT in excel format',
    'onsite_consultations_number' => 'Number of onsite consultations',

    'problem_type' => 'PROBLEM BY TYPE',
    'is_crisis' => 'Crisis call',
    'problem_details' => 'BREAKDOWN BY PROBLEM DETAILS',
    'gender' => 'DISTRIBUTION BY GENDER',
    'employee_or_family_member' => 'DIVISION BY EMPLOYEE / FAMILY MEMBER',
    'age' => 'AGE DISTRIBUTION',
    'language' => 'DISTRIBUTION BY LANGUAGE OF ADVICE',
    'source' => 'BREAKDOWN BY REFERRAL SOURCE',
    'type_of_problem' => 'DISTRIBUTION BY TYPE OF ADVICE',
    'place_of_receipt' => 'DISTRIBUTION BY CONTACTING OF THE PROGRAM',

    'statistics_are_rounded' => 'The mathematical rules of roundig are applied in the statistical summary. The data of the statistical summary is reserved by CGP Europe Kft. until the end of the given calendar year. If you wish to save the data included in the statistical summary, please, download the excel version in every quarter. ',

    'welcome' => [
        'page1' => [
            'title' => 'Welcome to the new client dashboard!',
            'text' => 'We are proud to present to you our completely renewed Client Dashboard. It took us nearly a year of digital development which ended with the renewal of the Client Dashboard. These developments included the improving of our EAP Online platform, updating the EAP chat application and the introduction of numerous new features to the my EAP app. The work was challenging but also inspiring at the same time. We hope that we didn’t only improve (and made more appealing) the looks of each platform but made them more accessible and more efficient for the users. The most exciting part of all this is the Client, on its new name/from now on called EAP Dashboard. Before exploring the new site, let us share with you some of the most important details of the development process.',
        ],
        'page2' => [
            'title' => 'A data is only useful if its easily comprehensible',
            'text' => 'The new EAP dashboards report menu is quickly and easily understandable. That way it provides the user a more informative depiction of the EAP program’s statistics.',
            'psychology' => 'Psychology',
        ],
        'page3' => [
            'title1' => 'New charts,',
            'title2' => 'New conclusions',
            'text' => 'The renewed report menu uses new and improved charts to showcase the EAP program’s statical datas, so that new conclusion can be made whilst using the program.',
            'finance' => 'finance',
            'female' => 'female',
        ],
        'page4' => [
            'title1' => 'A report system,',
            'title2' => 'that\'s for everybody\'s safety',
            'text' => 'The anonymity of those employees who use the EAP program is one the utmost important criteria of the consulting process but it’s also very important to us that the employees stay unidentifiable even from the reports statistical datas. To ensure the save of the employees/the identification won’t happen our reports do not contain regional locational datas.',
        ],
        'page5' => [
            'title1' => 'What’s even more informative than the reports?',
            'title2' => 'A mental health map',
            'text' => 'The new menu point will provide useful information about the current mental state of the company and will show those problems that the employees struggle the most with fighting and overcoming. It will give a detailed look at these problem’s natures and a percentage of how many people have been affected by it or them.',
        ],

        'continue_to_dashboard' => 'To the new EAP Dashboard.',
        'next' => 'Forward',
    ],

    'partial_sum' => 'Sum of Ongoing and Closed cases',
    'sum' => 'Sum of Ongoing, Closed, Interrupted and Clinet unreachable cases',

    '1_quarter' => 'Q1',
    '2_quarter' => 'Q2',
    '3_quarter' => 'Q3',
    '4_quarter' => 'Q4',

    'quarter' => 'Quarter',

    'in_progress_cases_info' => 'New cases received during the reporting period, with ongoing counselling sessions.',
    'closed_cases_info' => 'New cases received during the reporting period, counselling sessions finished.',
    'interrupted_cases_info' => ' New cases received during the reporting period, counselling interrupted by the employee due to reasons independent of expert’s will.',
    'client_unreachable_cases_info' => 'New cases received during the reporting period, in which the experts was not able to contact the employee.',
    'cumulated_info' => 'Closed cases + ongoing cases + interrupted cases + client unreachable cases + workshop participants + crisis participants
    + orientation participants + health day participants + expert outplacement participants + prizegame participants + eap online logins',
    'not_registered' => 'Not registered!',

    'total' => 'Total',

    'no_available_data' => 'There is currently no data available.',
    'no_data_to_enter' => 'No data to enter',

    'volume_request' => 'Employee headcount',
    'volume_request_closed' => 'The data recording period for the month has ended!',

    'consultations' => 'Consultations for Closed Cases',
    'consultations_ongoing' => 'Consultations for Active Cases by End of Reporting Period',
];
